export const PARAGRAPH_SUGGESTION_SYSTEM_PROMPT =
  "Split English passages into small memorization units by communicative purpose (greeting, opening, point, request, closing). Do not split by visual paragraph or equal length. Return only schema-valid output.";

export function buildParagraphSuggestionPrompt(text: string): string {
  return [
    "Input memorization passage:",
    text,
    "",
    "What a paragraph is:",
    "- A paragraph is one recitable memorization unit, not a document paragraph.",
    "- Group sentences that share one communicative purpose.",
    "- Start a new paragraph when the purpose changes.",
    "",
    "When to split:",
    '- Greeting or salutation (often its own unit, even if short: "Dear Alex,").',
    "- Courtesy opening vs stating purpose or background.",
    "- Background vs evaluation or main point.",
    "- Information vs a request or call to action.",
    "- Closing or sign-off. A short sign-off may stay with the last request.",
    "- Apply the same purpose-shift logic to emails, speeches, and prose.",
    "",
    "Size:",
    "- Prefer 1 to 3 sentences per paragraph.",
    "- Do not return two large halves of a long passage.",
    "- If two purposes are mixed, split. Do not split every sentence by default.",
    "",
    "Fidelity:",
    "- Preserve original English wording and order.",
    "- Cover the whole passage. Do not omit, rewrite, or duplicate text.",
    "- Greetings and sign-offs may be a sentence even if they are not a full clause.",
    "- Use null for translation unless the source text includes a clear translation.",
    "",
    "The number of paragraphs follows purpose shifts in the input, not a fixed count.",
    "Example — this email becomes 4 units, not 2 halves:",
    "1. Dear Alex,",
    "2. I hope this email finds you well. I am writing to follow up on our previous conversation regarding the new project timeline. We have reviewed the revised schedule and overall budget proposed by your team.",
    "3. Everything looks aligned with our goals, but we would like to clarify a few details before finalizing the contract. Specifically, we need to confirm the milestone dates for the first quarter deliverables.",
    "4. Could you please share your availability for a brief call later this week? Let me know if Thursday afternoon works for you. I look forward to your reply. Best regards, John.",
  ].join("\n");
}
